
[application]
    name = "边缘告警服务"
    port = 30000

[alert_tokens]
    # 飞书通知的token，置空的话就走夜莺推送里面的token
    feishu_rebot_token='36af9463-f523-461c-962c-18f2a01211d5,36af9463-f523-461c-962c-18f2a01211d5,36af9463-f523-461c-962c-18f2a01211d5'

# 与grafana告警约束的tag标记
[mysql_slow_query]
    # 慢查询告警标记，做二次处理
    tag = "MSQ"
    # 全局的慢查询时间阈值 单位是秒
    long_query_time = 10
    # 接到慢查询告警之后，往前追溯多久，单位是秒
    retrospect_time = 60